export const partTypes = {
        eye: 1,
        mouth: 2,
        hat: 3,
        weapon: 4,
        ear: 5,
        tail: 6,
    },
    classes = { mage: 1, warrior: 2, support: 3, ranger: 4, assassin: 5 },
    types = { normal: 0, legend: 1 },
    factions = { thunder: 1, fire: 2, earth: 3, wind: 4, water: 5, yinyang: 6 },
    lifeStages = { newborn: 1, adult: 2 },
    partArray = ['eyes', 'mouth', 'hair', 'hand', 'ears', 'tail'],
    importantPartArray = [
        { name: 'eyes', id: 1 },
        { name: 'hair', id: 3 },
        { name: 'hand', id: 4 },
        { name: 'tail', id: 6 },
    ];
export const parts = {
    1: {
        id: 1,
        part: 5,
        class: 4,
        type: 0,
        name: 'Norwegian',
        pose: 1,
    },
    2: {
        id: 2,
        part: 1,
        class: 4,
        type: 0,
        name: 'Roundish',
        pose: 1,
    },
    3: {
        id: 3,
        part: 2,
        class: 4,
        type: 0,
        name: 'Smiley',
        pose: 1,
    },
    4: {
        id: 4,
        part: 3,
        class: 4,
        type: 0,
        name: 'Spiky',
        pose: 1,
    },
    5: {
        id: 5,
        part: 6,
        class: 4,
        type: 0,
        name: 'Trident',
        pose: 1,
    },
    6: {
        id: 6,
        part: 4,
        class: 4,
        type: 0,
        name: 'Shuriken',
        pose: 1,
    },
    7: {
        id: 7,
        part: 5,
        class: 5,
        type: 0,
        name: 'Birman',
        pose: 1,
    },
    8: {
        id: 8,
        part: 1,
        class: 5,
        type: 0,
        name: 'Squinting',
        pose: 1,
    },
    9: {
        id: 9,
        part: 2,
        class: 5,
        type: 0,
        name: 'Straight',
        pose: 1,
    },
    10: {
        id: 10,
        part: 3,
        class: 5,
        type: 0,
        name: 'Highlight',
        pose: 1,
    },
    11: {
        id: 11,
        part: 6,
        class: 5,
        type: 0,
        name: 'Manx',
        pose: 1,
    },
    12: {
        id: 12,
        part: 4,
        class: 5,
        type: 0,
        name: 'Kunai',
        pose: 1,
    },
    13: {
        id: 13,
        part: 5,
        class: 1,
        type: 0,
        name: 'Folded',
        pose: 1,
    },
    14: {
        id: 14,
        part: 1,
        class: 1,
        type: 0,
        name: 'Doctor',
        pose: 1,
    },
    15: {
        id: 15,
        part: 2,
        class: 1,
        type: 0,
        name: 'Smallie',
        pose: 1,
    },
    16: {
        id: 16,
        part: 3,
        class: 1,
        type: 0,
        name: 'Long',
        pose: 1,
    },
    17: {
        id: 17,
        part: 6,
        class: 1,
        type: 0,
        name: 'Pixie',
        pose: 1,
    },
    18: {
        id: 18,
        part: 4,
        class: 1,
        type: 0,
        name: 'Angel',
        pose: 1,
    },
    19: {
        id: 19,
        part: 5,
        class: 3,
        type: 0,
        name: 'Cobby',
        pose: 1,
    },
    20: {
        id: 20,
        part: 1,
        class: 3,
        type: 0,
        name: 'Flirt',
        pose: 1,
    },
    21: {
        id: 21,
        part: 2,
        class: 3,
        type: 0,
        name: 'Curved',
        pose: 1,
    },
    22: {
        id: 22,
        part: 3,
        class: 3,
        type: 0,
        name: 'Dumb',
        pose: 1,
    },
    23: {
        id: 23,
        part: 6,
        class: 3,
        type: 0,
        name: 'Cymric',
        pose: 1,
    },
    24: {
        id: 24,
        part: 4,
        class: 3,
        type: 0,
        name: 'Watermelon',
        pose: 1,
    },
    25: {
        id: 25,
        part: 5,
        class: 2,
        type: 0,
        name: 'Scottish',
        pose: 1,
    },
    26: {
        id: 26,
        part: 1,
        class: 2,
        type: 0,
        name: 'Cyclopes',
        pose: 1,
    },
    27: {
        id: 27,
        part: 2,
        class: 2,
        type: 0,
        name: 'Dash',
        pose: 1,
    },
    28: {
        id: 28,
        part: 3,
        class: 2,
        type: 0,
        name: 'Punk',
        pose: 1,
    },
    29: {
        id: 29,
        part: 6,
        class: 2,
        type: 0,
        name: 'Cloudy',
        pose: 1,
    },
    30: {
        id: 30,
        part: 4,
        class: 2,
        type: 0,
        name: 'Matchet',
        pose: 1,
    },
    31: {
        id: 31,
        part: 5,
        class: 4,
        type: 1,
        name: 'Siberian',
        pose: 1,
    },
    32: {
        id: 32,
        part: 1,
        class: 4,
        type: 0,
        name: 'Starry',
        pose: 1,
    },
    33: {
        id: 33,
        part: 2,
        class: 4,
        type: 1,
        name: 'Haha',
        pose: 1,
    },
    34: {
        id: 34,
        part: 3,
        class: 4,
        type: 0,
        name: 'Bouffant',
        pose: 1,
    },
    35: {
        id: 35,
        part: 6,
        class: 4,
        type: 0,
        name: 'Aerial',
        pose: 1,
    },
    36: {
        id: 36,
        part: 4,
        class: 4,
        type: 0,
        name: 'Windmill',
        pose: 1,
    },
    37: {
        id: 37,
        part: 5,
        class: 5,
        type: 1,
        name: 'Curl',
        pose: 1,
    },
    38: {
        id: 38,
        part: 1,
        class: 5,
        type: 0,
        name: 'Piggy',
        pose: 1,
    },
    39: {
        id: 39,
        part: 2,
        class: 5,
        type: 0,
        name: 'Secret',
        pose: 1,
    },
    40: {
        id: 40,
        part: 3,
        class: 5,
        type: 0,
        name: 'Bun',
        pose: 1,
    },
    41: {
        id: 41,
        part: 6,
        class: 5,
        type: 0,
        name: 'Bullet',
        pose: 1,
    },
    42: {
        id: 42,
        part: 4,
        class: 5,
        type: 0,
        name: 'Blade',
        pose: 1,
    },
    43: {
        id: 43,
        part: 5,
        class: 1,
        type: 0,
        name: 'Ragdoll',
        pose: 1,
    },
    44: {
        id: 44,
        part: 1,
        class: 1,
        type: 0,
        name: 'Sunken',
        pose: 1,
    },
    45: {
        id: 45,
        part: 2,
        class: 1,
        type: 0,
        name: 'Mountain',
        pose: 1,
    },
    46: {
        id: 46,
        part: 3,
        class: 1,
        type: 0,
        name: 'Pointy',
        pose: 1,
    },
    47: {
        id: 47,
        part: 6,
        class: 1,
        type: 0,
        name: 'Green',
        pose: 1,
    },
    48: {
        id: 48,
        part: 4,
        class: 1,
        type: 1,
        name: 'Twin',
        pose: 1,
    },
    49: {
        id: 49,
        part: 5,
        class: 3,
        type: 1,
        name: 'LaPerm',
        pose: 1,
    },
    50: {
        id: 50,
        part: 1,
        class: 3,
        type: 0,
        name: 'Bug',
        pose: 1,
    },
    51: {
        id: 51,
        part: 2,
        class: 3,
        type: 0,
        name: 'Devil',
        pose: 1,
    },
    52: {
        id: 52,
        part: 3,
        class: 3,
        type: 0,
        name: 'Sushi',
        pose: 1,
    },
    53: {
        id: 53,
        part: 6,
        class: 3,
        type: 0,
        name: 'Stumpy',
        pose: 1,
    },
    54: {
        id: 54,
        part: 4,
        class: 3,
        type: 0,
        name: 'Ice cream',
        pose: 1,
    },
    55: {
        id: 55,
        part: 5,
        class: 2,
        type: 0,
        name: 'Highlander',
        pose: 1,
    },
    56: {
        id: 56,
        part: 1,
        class: 2,
        type: 0,
        name: 'Scouter',
        pose: 1,
    },
    57: {
        id: 57,
        part: 2,
        class: 2,
        type: 0,
        name: 'Sadness',
        pose: 1,
    },
    58: {
        id: 58,
        part: 3,
        class: 2,
        type: 0,
        name: 'Bird',
        pose: 1,
    },
    59: {
        id: 59,
        part: 6,
        class: 2,
        type: 0,
        name: 'T-rex',
        pose: 1,
    },
    60: {
        id: 60,
        part: 4,
        class: 2,
        type: 0,
        name: 'Axe',
        pose: 1,
    },
    61: {
        id: 61,
        part: 5,
        class: 4,
        type: 0,
        name: 'Foxy',
        pose: 1,
    },
    62: {
        id: 62,
        part: 1,
        class: 4,
        type: 1,
        name: 'Shutter',
        pose: 1,
    },
    63: {
        id: 63,
        part: 2,
        class: 4,
        type: 0,
        name: 'Bear',
        pose: 1,
    },
    64: {
        id: 64,
        part: 3,
        class: 4,
        type: 0,
        name: 'Dragon',
        pose: 1,
    },
    65: {
        id: 65,
        part: 6,
        class: 4,
        type: 1,
        name: 'Skeleton',
        pose: 1,
    },
    66: {
        id: 66,
        part: 4,
        class: 4,
        type: 0,
        name: 'Chicken',
        pose: 1,
    },
    67: {
        id: 67,
        part: 4,
        class: 4,
        type: 0,
        name: 'Pan',
        pose: 1,
    },
    68: {
        id: 68,
        part: 4,
        class: 4,
        type: 0,
        name: 'Anchor',
        pose: 1,
    },
    69: {
        id: 69,
        part: 4,
        class: 4,
        type: 0,
        name: 'Brick',
        pose: 1,
    },
    70: {
        id: 70,
        part: 4,
        class: 4,
        type: 0,
        name: 'Cup',
        pose: 1,
    },
    71: {
        id: 71,
        part: 4,
        class: 4,
        type: 0,
        name: 'TNT',
        pose: 1,
    },
    72: {
        id: 72,
        part: 4,
        class: 4,
        type: 1,
        name: 'Rugby Ball',
        pose: 1,
    },
    73: {
        id: 73,
        part: 4,
        class: 4,
        type: 0,
        name: 'Boomerang',
        pose: 1,
    },
    74: {
        id: 74,
        part: 4,
        class: 4,
        type: 0,
        name: 'Biggie',
        pose: 1,
    },
    75: {
        id: 75,
        part: 3,
        class: 4,
        type: 1,
        name: 'Pirate',
        pose: 2,
    },
    76: {
        id: 76,
        part: 4,
        class: 4,
        type: 0,
        name: 'Gun',
        pose: 2,
    },
    77: {
        id: 77,
        part: 4,
        class: 4,
        type: 1,
        name: 'AK47',
        pose: 3,
    },
    78: {
        id: 78,
        part: 4,
        class: 4,
        type: 0,
        name: 'Riffle',
        pose: 3,
    },
    79: {
        id: 79,
        part: 3,
        class: 4,
        type: 0,
        name: 'Robin',
        pose: 4,
    },
    80: {
        id: 80,
        part: 4,
        class: 4,
        type: 1,
        name: 'Bow',
        pose: 4,
    },
    81: {
        id: 81,
        part: 4,
        class: 3,
        type: 0,
        name: 'Pump',
        pose: 1,
    },
    82: {
        id: 82,
        part: 4,
        class: 4,
        type: 0,
        name: 'Sniper',
        pose: 3,
    },
    83: {
        id: 83,
        part: 4,
        class: 3,
        type: 0,
        name: 'Wrench',
        pose: 1,
    },
    84: {
        id: 84,
        part: 4,
        class: 2,
        type: 0,
        name: 'Spear',
        pose: 2,
    },
    85: {
        id: 85,
        part: 4,
        class: 2,
        type: 0,
        name: 'Hammer',
        pose: 1,
    },
    86: {
        id: 86,
        part: 4,
        class: 3,
        type: 1,
        name: 'Medic',
        pose: 1,
    },
    87: {
        id: 87,
        part: 4,
        class: 3,
        type: 0,
        name: 'Sword',
        pose: 1,
    },
    88: {
        id: 88,
        part: 4,
        class: 3,
        type: 1,
        name: 'Golf Club',
        pose: 1,
    },
    89: {
        id: 89,
        part: 4,
        class: 3,
        type: 0,
        name: 'Hook',
        pose: 1,
    },
    90: {
        id: 90,
        part: 4,
        class: 2,
        type: 1,
        name: 'Broomstick',
        pose: 2,
    },
    91: {
        id: 91,
        part: 4,
        class: 2,
        type: 0,
        name: 'Scythe',
        pose: 2,
    },
    92: {
        id: 92,
        part: 5,
        class: 5,
        type: 0,
        name: 'Pink',
        pose: 1,
    },
    93: {
        id: 93,
        part: 1,
        class: 5,
        type: 1,
        name: 'Paint',
        pose: 1,
    },
    94: {
        id: 94,
        part: 2,
        class: 5,
        type: 0,
        name: 'Fang',
        pose: 1,
    },
    95: {
        id: 95,
        part: 3,
        class: 5,
        type: 1,
        name: 'Goat',
        pose: 1,
    },
    96: {
        id: 96,
        part: 6,
        class: 5,
        type: 0,
        name: 'Jelly',
        pose: 1,
    },
    97: {
        id: 97,
        part: 4,
        class: 5,
        type: 0,
        name: 'Crab',
        pose: 1,
    },
    98: {
        id: 98,
        part: 4,
        class: 5,
        type: 0,
        name: 'No entry',
        pose: 1,
    },
    99: {
        id: 99,
        part: 4,
        class: 5,
        type: 0,
        name: 'Brush',
        pose: 1,
    },
    100: {
        id: 100,
        part: 4,
        class: 2,
        type: 0,
        name: 'Hilt',
        pose: 3,
    },
    101: {
        id: 101,
        part: 4,
        class: 2,
        type: 0,
        name: 'Katana',
        pose: 3,
    },
    102: {
        id: 102,
        part: 4,
        class: 1,
        type: 0,
        name: 'Pawn',
        pose: 1,
    },
    103: {
        id: 103,
        part: 4,
        class: 1,
        type: 0,
        name: 'Guitar',
        pose: 1,
    },
    104: {
        id: 104,
        part: 4,
        class: 1,
        type: 0,
        name: 'Toilet',
        pose: 1,
    },
    105: {
        id: 105,
        part: 4,
        class: 1,
        type: 0,
        name: 'Stick',
        pose: 1,
    },
    106: {
        id: 106,
        part: 4,
        class: 5,
        type: 1,
        name: 'Boxing',
        pose: 2,
    },
    107: {
        id: 107,
        part: 4,
        class: 5,
        type: 1,
        name: 'Club',
        pose: 1,
    },
    108: {
        id: 108,
        part: 4,
        class: 2,
        type: 1,
        name: 'Lightsaber',
        pose: 3,
    },
    109: {
        id: 109,
        part: 4,
        class: 2,
        type: 0,
        name: 'Ruyi',
        pose: 3,
    },
    110: {
        id: 110,
        part: 5,
        class: 5,
        type: 0,
        name: 'Hairy',
        pose: 1,
    },
    111: {
        id: 111,
        part: 5,
        class: 5,
        type: 0,
        name: 'Bambi',
        pose: 1,
    },
    112: {
        id: 112,
        part: 5,
        class: 5,
        type: 0,
        name: 'Mini',
        pose: 1,
    },
    113: {
        id: 113,
        part: 5,
        class: 1,
        type: 0,
        name: 'Jaguar',
        pose: 1,
    },
    114: {
        id: 114,
        part: 5,
        class: 1,
        type: 0,
        name: 'Deer',
        pose: 1,
    },
    115: {
        id: 115,
        part: 4,
        class: 5,
        type: 0,
        name: 'Short Stick',
        pose: 1,
    },
    116: {
        id: 116,
        part: 4,
        class: 1,
        type: 1,
        name: 'Turtle',
        pose: 1,
    },
    117: {
        id: 117,
        part: 4,
        class: 1,
        type: 0,
        name: 'Dracula',
        pose: 1,
    },
    118: {
        id: 118,
        part: 4,
        class: 1,
        type: 0,
        name: 'Hive',
        pose: 1,
    },
    119: {
        id: 119,
        part: 6,
        class: 5,
        type: 0,
        name: 'Mermaid',
        pose: 1,
    },
    120: {
        id: 120,
        part: 6,
        class: 5,
        type: 0,
        name: 'Panther',
        pose: 1,
    },
    121: {
        id: 121,
        part: 6,
        class: 5,
        type: 0,
        name: 'Snake',
        pose: 1,
    },
    122: {
        id: 122,
        part: 6,
        class: 1,
        type: 0,
        name: 'Roll',
        pose: 1,
    },
    123: {
        id: 123,
        part: 6,
        class: 1,
        type: 0,
        name: 'Horse',
        pose: 1,
    },
    124: {
        id: 124,
        part: 6,
        class: 2,
        type: 0,
        name: 'Roster',
        pose: 1,
    },
    125: {
        id: 125,
        part: 6,
        class: 2,
        type: 0,
        name: 'Scorpion',
        pose: 1,
    },
    126: {
        id: 126,
        part: 6,
        class: 2,
        type: 0,
        name: 'Cheese',
        pose: 1,
    },
    127: {
        id: 127,
        part: 6,
        class: 1,
        type: 1,
        name: 'Maple',
        pose: 1,
    },
    128: {
        id: 128,
        part: 2,
        class: 1,
        type: 0,
        name: 'Rat',
        pose: 1,
    },
    129: {
        id: 129,
        part: 2,
        class: 1,
        type: 1,
        name: 'Whistle',
        pose: 1,
    },
    130: {
        id: 130,
        part: 2,
        class: 3,
        type: 0,
        name: 'Clown',
        pose: 1,
    },
    131: {
        id: 131,
        part: 2,
        class: 5,
        type: 1,
        name: 'Baby',
        pose: 1,
    },
    132: {
        id: 132,
        part: 2,
        class: 5,
        type: 0,
        name: 'Old',
        pose: 1,
    },
    133: {
        id: 133,
        part: 2,
        class: 1,
        type: 0,
        name: 'Cute',
        pose: 1,
    },
    134: {
        id: 134,
        part: 2,
        class: 2,
        type: 1,
        name: 'Mustache',
        pose: 1,
    },
    135: {
        id: 135,
        part: 2,
        class: 2,
        type: 0,
        name: 'Pig',
        pose: 1,
    },
    136: {
        id: 136,
        part: 2,
        class: 2,
        type: 0,
        name: 'Big',
        pose: 1,
    },
    137: {
        id: 137,
        part: 2,
        class: 2,
        type: 0,
        name: 'Hold',
        pose: 1,
    },
    138: {
        id: 138,
        part: 2,
        class: 3,
        type: 0,
        name: 'One',
        pose: 1,
    },
    139: {
        id: 139,
        part: 2,
        class: 3,
        type: 0,
        name: 'Dripping',
        pose: 1,
    },
    140: {
        id: 140,
        part: 2,
        class: 5,
        type: 0,
        name: 'Sewn',
        pose: 1,
    },
    141: {
        id: 141,
        part: 2,
        class: 1,
        type: 0,
        name: 'Triangle',
        pose: 1,
    },
    142: {
        id: 142,
        part: 2,
        class: 3,
        type: 1,
        name: 'Duck',
        pose: 1,
    },
    143: {
        id: 143,
        part: 2,
        class: 5,
        type: 0,
        name: 'Cat',
        pose: 1,
    },
    144: {
        id: 144,
        part: 2,
        class: 5,
        type: 0,
        name: 'Spot',
        pose: 1,
    },
    145: {
        id: 145,
        part: 2,
        class: 5,
        type: 0,
        name: 'Lipstick',
        pose: 1,
    },
    146: {
        id: 146,
        part: 2,
        class: 5,
        type: 0,
        name: 'Shark',
        pose: 1,
    },
    147: {
        id: 147,
        part: 6,
        class: 2,
        type: 1,
        name: 'Bluefin',
        pose: 1,
    },
    148: {
        id: 148,
        part: 6,
        class: 3,
        type: 0,
        name: 'Squirrel',
        pose: 1,
    },
    149: {
        id: 149,
        part: 6,
        class: 3,
        type: 0,
        name: 'Pangolin',
        pose: 1,
    },
    150: {
        id: 150,
        part: 6,
        class: 3,
        type: 1,
        name: 'Dino',
        pose: 1,
    },
    151: {
        id: 151,
        part: 6,
        class: 5,
        type: 1,
        name: 'Racoon',
        pose: 1,
    },
    152: {
        id: 152,
        part: 6,
        class: 5,
        type: 0,
        name: 'Flower',
        pose: 1,
    },
    153: {
        id: 153,
        part: 6,
        class: 3,
        type: 0,
        name: 'Bulb',
        pose: 1,
    },
    154: {
        id: 154,
        part: 6,
        class: 5,
        type: 0,
        name: 'Pine',
        pose: 1,
    },
    155: {
        id: 155,
        part: 6,
        class: 5,
        type: 0,
        name: 'Chilli',
        pose: 1,
    },
    156: {
        id: 156,
        part: 3,
        class: 5,
        type: 0,
        name: 'Wukong',
        pose: 1,
    },
    157: {
        id: 157,
        part: 3,
        class: 5,
        type: 0,
        name: 'Santa',
        pose: 1,
    },
    158: {
        id: 158,
        part: 3,
        class: 1,
        type: 0,
        name: 'Poo',
        pose: 1,
    },
    159: {
        id: 159,
        part: 3,
        class: 1,
        type: 0,
        name: 'Wavy',
        pose: 1,
    },
    160: {
        id: 160,
        part: 3,
        class: 1,
        type: 1,
        name: 'Hippie',
        pose: 1,
    },
    161: {
        id: 161,
        part: 3,
        class: 1,
        type: 0,
        name: 'Samurai',
        pose: 1,
    },
    162: {
        id: 162,
        part: 3,
        class: 2,
        type: 0,
        name: 'Nurse',
        pose: 1,
    },
    163: {
        id: 163,
        part: 3,
        class: 2,
        type: 1,
        name: 'Guan Yu',
        pose: 1,
    },
    164: {
        id: 164,
        part: 3,
        class: 2,
        type: 0,
        name: 'Party',
        pose: 1,
    },
    165: {
        id: 165,
        part: 3,
        class: 3,
        type: 0,
        name: 'Angel ring',
        pose: 1,
    },
    166: {
        id: 166,
        part: 3,
        class: 2,
        type: 0,
        name: 'Cake',
        pose: 1,
    },
    167: {
        id: 167,
        part: 3,
        class: 3,
        type: 1,
        name: 'Snorkel',
        pose: 1,
    },
    168: {
        id: 168,
        part: 3,
        class: 3,
        type: 0,
        name: 'Chef',
        pose: 1,
    },
    169: {
        id: 169,
        part: 3,
        class: 3,
        type: 0,
        name: 'Conical',
        pose: 1,
    },
    170: {
        id: 170,
        part: 3,
        class: 5,
        type: 0,
        name: 'Hopter',
        pose: 1,
    },
    171: {
        id: 171,
        part: 3,
        class: 5,
        type: 0,
        name: 'Nest',
        pose: 1,
    },
    172: {
        id: 172,
        part: 3,
        class: 5,
        type: 0,
        name: 'Burger',
        pose: 1,
    },
    173: {
        id: 173,
        part: 3,
        class: 5,
        type: 0,
        name: 'Helmet',
        pose: 1,
    },
    174: {
        id: 174,
        part: 6,
        class: 1,
        type: 0,
        name: 'Bread',
        pose: 1,
    },
    175: {
        id: 175,
        part: 5,
        class: 1,
        type: 1,
        name: 'Rabbit',
        pose: 1,
    },
    176: {
        id: 176,
        part: 5,
        class: 1,
        type: 0,
        name: 'Rings',
        pose: 1,
    },
    177: {
        id: 177,
        part: 5,
        class: 2,
        type: 0,
        name: 'Edge',
        pose: 1,
    },
    178: {
        id: 178,
        part: 5,
        class: 2,
        type: 0,
        name: 'Star',
        pose: 1,
    },
    179: {
        id: 179,
        part: 5,
        class: 2,
        type: 0,
        name: 'Tiny Star',
        pose: 1,
    },
    180: {
        id: 180,
        part: 5,
        class: 2,
        type: 0,
        name: 'Moon',
        pose: 1,
    },
    181: {
        id: 181,
        part: 5,
        class: 2,
        type: 1,
        name: 'Alien',
        pose: 1,
    },
    182: {
        id: 182,
        part: 5,
        class: 2,
        type: 0,
        name: 'Purple',
        pose: 1,
    },
    183: {
        id: 183,
        part: 5,
        class: 2,
        type: 0,
        name: 'Robot',
        pose: 1,
    },
    184: {
        id: 184,
        part: 5,
        class: 3,
        type: 0,
        name: 'Gemstone',
        pose: 1,
    },
    185: {
        id: 185,
        part: 5,
        class: 2,
        type: 1,
        name: 'Fish',
        pose: 1,
    },
    186: {
        id: 186,
        part: 5,
        class: 5,
        type: 0,
        name: 'Puppy',
        pose: 1,
    },
    187: {
        id: 187,
        part: 5,
        class: 5,
        type: 0,
        name: 'Leaf',
        pose: 1,
    },
    188: {
        id: 188,
        part: 5,
        class: 5,
        type: 0,
        name: 'Shorty',
        pose: 1,
    },
    189: {
        id: 189,
        part: 1,
        class: 5,
        type: 0,
        name: 'Owl',
        pose: 1,
    },
    190: {
        id: 190,
        part: 1,
        class: 5,
        type: 0,
        name: 'Monocle',
        pose: 1,
    },
    191: {
        id: 191,
        part: 1,
        class: 5,
        type: 0,
        name: 'Mask',
        pose: 1,
    },
    192: {
        id: 192,
        part: 1,
        class: 1,
        type: 0,
        name: 'Reader',
        pose: 1,
    },
    193: {
        id: 193,
        part: 1,
        class: 1,
        type: 0,
        name: 'Dollars',
        pose: 1,
    },
    194: {
        id: 194,
        part: 1,
        class: 1,
        type: 1,
        name: 'Blind',
        pose: 1,
    },
    195: {
        id: 195,
        part: 1,
        class: 1,
        type: 0,
        name: 'Red',
        pose: 1,
    },
    196: {
        id: 196,
        part: 1,
        class: 2,
        type: 0,
        name: 'Crying',
        pose: 1,
    },
    197: {
        id: 197,
        part: 1,
        class: 2,
        type: 0,
        name: 'Love',
        pose: 1,
    },
    198: {
        id: 198,
        part: 1,
        class: 2,
        type: 1,
        name: 'Scar',
        pose: 1,
    },
    199: {
        id: 199,
        part: 1,
        class: 2,
        type: 0,
        name: 'Phoenix',
        pose: 1,
    },
    200: {
        id: 200,
        part: 1,
        class: 3,
        type: 0,
        name: 'Tiger',
        pose: 1,
    },
    201: {
        id: 201,
        part: 1,
        class: 3,
        type: 0,
        name: 'Crayon',
        pose: 1,
    },
    202: {
        id: 202,
        part: 1,
        class: 3,
        type: 1,
        name: 'Player',
        pose: 1,
    },
    203: {
        id: 203,
        part: 1,
        class: 3,
        type: 0,
        name: 'Eagle',
        pose: 1,
    },
    204: {
        id: 204,
        part: 1,
        class: 5,
        type: 0,
        name: 'Fox',
        pose: 1,
    },
    205: {
        id: 205,
        part: 1,
        class: 5,
        type: 0,
        name: 'Zorro',
        pose: 1,
    },
    206: {
        id: 206,
        part: 1,
        class: 5,
        type: 0,
        name: 'Yellow',
        pose: 1,
    },
    207: {
        id: 207,
        part: 1,
        class: 5,
        type: 0,
        name: 'Flash',
        pose: 1,
    },
};
